MAE-377: Always set offline auto renew when payment plan is selected
compucorp/uk.co.compucorp.membershipextras pull request #288
Opened 2020-09-07 16:47 UTC by erawat

## Overview
_A brief description of the pull request. Try to keep it non-technical._

## Before
_The current status. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## After
_What has been changed. Please provide screenshots or gifs ([LICEcap](http://www.cockos.com/licecap/), [SilentCast](https://github.com/colinkeenan/silentcast)) where appropriate._

## Technical Details
_If the PR introduces noteworthy technical changes, please describe them here. Provide code snippets if necessary_

### Core overrides
_If the PR overrides/patches a core file, then please explain here, for each file:_

1. _Which file it is_
2. _The reason why it was overridden/patched_
3. _What the override/patch consists of_

## Comments
_Anything else you would like the reviewer to note_

2020-09-09 18:39 UTC, omarabuhussein commented
some notes : 

1- CRM_MembershipExtras_Hook_PostProcess_MembershipOfflineAutoRenewProcessor class contain the following unused methods : **createRecurringSubscriptionLineItems** and **calculateMinimumFrequencyUnitAndInterval** so they should be removed. 

2- I would change the if statement inside CRM_MembershipExtras_Hook_PostProcess_MembershipOfflineAutoRenewProcessor to call the methods directly like this : 

```
if (!$this->isPaymentPlanWithAtLeastOneInstallment() || $this->isMembershipAlreadyAutoRenewed()) {
``` 

storing them in variables is unnecessary duplication.


3- I think that the commits are a little confusing and I would prefer some restructurings, so for example  : 

A-  These two commits should be combined and they should be the first commit : 

https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/48772e3fe8407cc3d82b4ef455436dc928804d31
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/39192d8a8fdfeeed7c94d8fc962c5611fb17e78b


B- and the 2nd commit should be these three  combined together : 

https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/5cc9c84f2e0e40c43e7bd9a2cc4134225853960a
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/8025feb7f861c5dfd12f1498a2e2856f668f4bbc
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/24187efb4618bfd8adfc8528a5c82d90a0253e11

along with my suggestions in point 1 and 2 above.

C- and the 3rd commit maybe this : 

https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/8db688e861a40322c3a45ae99a5973c6a3301d22

D- then maybe this 
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/ed90dbfa4ca98ef0dc75766693f37fac00a7bad5


E-and then the linter fixes :  https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/036c64c1cfea2f94f515c79731fb57e5f560da2d

2020-09-09 18:39 UTC, omarabuhussein requested changes
some notes : 

1- CRM_MembershipExtras_Hook_PostProcess_MembershipOfflineAutoRenewProcessor class contain the following unused methods : **createRecurringSubscriptionLineItems** and **calculateMinimumFrequencyUnitAndInterval** so they should be removed. 

2- I would change the if statement inside CRM_MembershipExtras_Hook_PostProcess_MembershipOfflineAutoRenewProcessor to call the methods directly like this : 

```
if (!$this->isPaymentPlanWithAtLeastOneInstallment() || $this->isMembershipAlreadyAutoRenewed()) {
``` 

storing them in variables is unnecessary duplication.


3- I think that the commits are a little confusing and I would prefer some restructurings, so for example  : 

A-  These two commits should be combined and they should be the first commit : 

https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/48772e3fe8407cc3d82b4ef455436dc928804d31
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/39192d8a8fdfeeed7c94d8fc962c5611fb17e78b


B- and the 2nd commit should be these three  combined together : 

https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/5cc9c84f2e0e40c43e7bd9a2cc4134225853960a
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/8025feb7f861c5dfd12f1498a2e2856f668f4bbc
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/24187efb4618bfd8adfc8528a5c82d90a0253e11

along with my suggestions in point 1 and 2 above.

C- and the 3rd commit maybe this : 

https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/8db688e861a40322c3a45ae99a5973c6a3301d22

D- then maybe this 
https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/ed90dbfa4ca98ef0dc75766693f37fac00a7bad5


E-and then the linter fixes :  https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/288/commits/036c64c1cfea2f94f515c79731fb57e5f560da2d

2020-09-10 09:12 UTC, erawat commented
> some notes :
> 
> 1- CRM_MembershipExtras_Hook_PostProcess_MembershipOfflineAutoRenewProcessor class contain the following unused methods : **createRecurringSubscriptionLineItems** and **calculateMinimumFrequencyUnitAndInterval** so they should be removed.
> 
> 2- I would change the if statement inside CRM_MembershipExtras_Hook_PostProcess_MembershipOfflineAutoRenewProcessor to call the methods directly like this :
> 
> ```
> if (!$this->isPaymentPlanWithAtLeastOneInstallment() || $this->isMembershipAlreadyAutoRenewed()) {
> ```
> 
> storing them in variables is unnecessary duplication.
> 
> 3- I think that the commits are a little confusing and I would prefer some restructurings, so for example :
> 
> A- These two commits should be combined and they should be the first commit :
> 
> [48772e3](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/48772e3fe8407cc3d82b4ef455436dc928804d31)
> [39192d8](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/39192d8a8fdfeeed7c94d8fc962c5611fb17e78b)
> 
> B- and the 2nd commit should be these three combined together :
> 
> [5cc9c84](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/5cc9c84f2e0e40c43e7bd9a2cc4134225853960a)
> [8025feb](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/8025feb7f861c5dfd12f1498a2e2856f668f4bbc)
> [24187ef](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/24187efb4618bfd8adfc8528a5c82d90a0253e11)
> 
> along with my suggestions in point 1 and 2 above.
> 
> C- and the 3rd commit maybe this :
> 
> [8db688e](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/8db688e861a40322c3a45ae99a5973c6a3301d22)
> 
> D- then maybe this
> [ed90dbf](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/ed90dbfa4ca98ef0dc75766693f37fac00a7bad5)
> 
> E-and then the linter fixes : [036c64c](https://github.com/compucorp/uk.co.compucorp.membershipextras/commit/036c64c1cfea2f94f515c79731fb57e5f560da2d)
> 
> also I am going tomorrow to review this PR : #265 again so you can write tests for this one (we need them as part of this PR)

@omarabuhussein  thanks for spotting point 1.  I refactor to code for point 1 and 2 as well as re-structure the git commits as per you suggested. 

I will wait for PR https://github.com/compucorp/uk.co.compucorp.membershipextras/pull/265 to be reviewed and merge to master, so we could ship the changes with unit tests.

2020-09-15 16:56 UTC, MiyaNoctem commented on CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessor.php
> +  private function isMembershipAlreadyAutoRenewed() {
The name of this function may lend itself for confusions, as it does not check if the membership has renewed automatically, as it implies. What it's really doing is checking if the membership is marked to auto-renew. So maybe we can change the method name to `isMembershipAlreadySetToAutoenew()`.

2020-09-15 16:56 UTC, MiyaNoctem commented on tests/phpunit/CRM/MembershipExtras/Hook/PostProcess/MembershipOfflineAutoRenewProcessorTest.php
> +   *
?

2020-09-16 10:37 UTC, MiyaNoctem approved these changes

2020-09-16 10:49 UTC, merged