MAE-479: Alter contribution receive date
compucorp/uk.co.compucorp.membershipextras pull request #352
Opened 2021-02-22 16:48 UTC by erawat

## Overview

Membership Extras version 5 hides contribution received date field on the user interface by default and the default value also set to sign up date. 

This PR adds logic to alter contribution receive date param to always use membership start date when creating payment plan on civicrm pre hook with contribution object

The contribution receive date param is used as

- A received date for first contribution in a payment plan
- Payment plan start date 

## Before

- First contribution receive date in the payment plan is always set as sign up date

## After

- First contribution receive date in the payment plan will always be set as membership start date 

## Technical Details

Alter receive date param in the pre hook is preferred to create a logic in the UI set receive date as membership start date or membership join date as we can ensure that the first contribution receive date will always set as membership start date as well as the test can be done via unit test.

2021-02-22 16:49 UTC, jamienovick commented
Does direct debit start date logic interact with this? @erawat thanks

2021-02-22 16:56 UTC, erawat commented
> Does direct debit start date logic interact with this? @erawat thanks

@jamienovick  yes, it interacts with this.  The hook that alters DD received date will trigger and alter this.

2021-02-22 17:57 UTC, jamienovick commented
Ok, is there anyway to bake in some tests around that to make sure that the two hooks don't fire in a different order if Civi changes something?

2021-02-22 18:07 UTC, erawat commented
> Ok, is there anyway to bake in some tests around that to make sure that the two hooks don't fire in a different order if Civi changes something? @erawat

@jamienovick the hook that alters DD contribution received date or any other extensions is dispatched inside this hook and always runs before creating recurring contribution which after the received date is altered with membership start date.

2021-02-23 12:46 UTC, omarabuhussein requested changes

2021-02-23 12:46 UTC, omarabuhussein commented on CRM/MembershipExtras/Hook/Pre/MembershipPaymentPlanProcessor/Contribution.php
> +  private function alterRecievedDate() {
this does not seem that it will work well when we renew with "don't update membership start date on renewal" setting

2021-02-23 18:29 UTC, closed without merging